命令稿啟動於 2017年03月13日 (週一) 23時49分01秒
]0;wu_yu_chen@wu-yu-chen: ~/My_Github/lab1wu_yu_chen@wu-yu-chen:~/My_Github/lab1$ g++ A.cpp -o A
]0;wu_yu_chen@wu-yu-chen: ~/My_Github/lab1wu_yu_chen@wu-yu-chen:~/My_Github/lab1$ ./A
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;wu_yu_chen@wu-yu-chen: ~/My_Github/lab1wu_yu_chen@wu-yu-chen:~/My_Github/lab1$ exit

命令稿已於 2017年03月13日 (週一) 23時49分14秒
 完成